services:
  auth-service-migration:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
      target: builder
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: pnpm --filter auth-service run prisma:migrate
    depends_on:
      - postgres
    networks:
      - app-network

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      - PORT=${AUTH_SERVICE_PORT}
    env_file:
      - ./.env
    depends_on:
      - auth-service-migration
      - redis
    networks:
      - app-network

  job-service:
    tty: true  # Allocates a pseudo-TTY
    stdin_open: true
    build:
      context: .
      dockerfile: services/job-service/Dockerfile
      target: dev
    volumes:
       - pnpm-store:/pnpm/store
    ports:
      - "${JOB_SERVICE_PORT}:${JOB_SERVICE_PORT}"
    develop:
      watch:
        - action: sync
          path: ./services/job-service/src
          target: /usr/src/app/services/job-service/src
          ignore:
            - node_modules/
        - action: sync
          path: ./packages
          target: /usr/src/app/packages
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/job-service/package.json
        - action: sync
          path: ./tsconfig.json
          target: /usr/src/app/tsconfig.json
    env_file:
      - ./services/job-service/.env
      - ./.env
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  thumbnail-worker:
    build:
      context: .
      dockerfile: services/thumbnail-worker/Dockerfile
    env_file:
      - ./.env
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  postgres_data:
  redis_data:
  pnpm-store:


