import { EventEmitter } from 'events';
import * as fs from 'fs';
import { injectable } from 'tsyringe';

import type { ITranscriptionService } from '@subtitle-worker/interfaces/transcription.interface';

@injectable()
export class MockTranscriptionService
  extends EventEmitter
  implements ITranscriptionService
{
  constructor() {
    super();
  }

  public async transcribe(audioPath: string, language: string): Promise<any> {
    try {
      this.emit('progress', 0);
      const audioBuffer = await fs.promises.readFile(audioPath);
      const { result, error }: any = {
        result: {
          metadata: {
            transaction_key: 'deprecated',
            request_id: 'b300c80b-8b5d-4d36-a619-7031da773976',
            sha256:
              'eb507201f07f8c906682057a3ffaec939db18c6256ffa52b2d7e7b0b538b75be',
            created: '2025-04-25T23:31:10.589Z',
            duration: 118.09669,
            channels: 1,
            models: ['1abfe86b-e047-4eed-858a-35e5625b41ee'],
            model_info: {
              '1abfe86b-e047-4eed-858a-35e5625b41ee': {
                name: '2-general-nova',
                version: '2024-01-06.5664',
                arch: 'nova-2',
              },
            },
          },
          results: {
            channels: [
              {
                alternatives: [
                  {
                    transcript:
                      "Some call me nature. Others call me mother nature. I've been here for over four and a half billion years. Twenty two thousand five hundred times longer than you. I don't really need people, but people need me. Yes, your future depends on me. When I thrive, you thrive. When I falter, you falter. Or worse. But I've been here for eons. I have fed species greater than you, and I have starved species greater than you. My oceans, my soil, my flowing streams, my forests, they all can take you or leave you. How you choose to live each day, whether you regard or disregard me, doesn't really matter to me, one way or the other. Your actions will determine your fate, not mine. I am nature. I will go on. I am prepared to evolve. Are you?",
                    confidence: 0.99881077,
                    words: [
                      {
                        word: 'some',
                        start: 3.84,
                        end: 4.16,
                        confidence: 0.82021403,
                        punctuated_word: 'Some',
                      },
                      {
                        word: 'call',
                        start: 4.16,
                        end: 4.4,
                        confidence: 0.9992494,
                        punctuated_word: 'call',
                      },
                      {
                        word: 'me',
                        start: 4.4,
                        end: 4.64,
                        confidence: 0.99974924,
                        punctuated_word: 'me',
                      },
                      {
                        word: 'nature',
                        start: 4.64,
                        end: 5.14,
                        confidence: 0.85333455,
                        punctuated_word: 'nature.',
                      },
                      {
                        word: 'others',
                        start: 11.5199995,
                        end: 12,
                        confidence: 0.9610789,
                        punctuated_word: 'Others',
                      },
                      {
                        word: 'call',
                        start: 12,
                        end: 12.32,
                        confidence: 0.99918526,
                        punctuated_word: 'call',
                      },
                      {
                        word: 'me',
                        start: 12.32,
                        end: 12.82,
                        confidence: 0.9996667,
                        punctuated_word: 'me',
                      },
                      {
                        word: 'mother',
                        start: 13.36,
                        end: 13.86,
                        confidence: 0.61809415,
                        punctuated_word: 'mother',
                      },
                      {
                        word: 'nature',
                        start: 14.184999,
                        end: 14.684999,
                        confidence: 0.99900067,
                        punctuated_word: 'nature.',
                      },
                      {
                        word: "i've",
                        start: 17.465,
                        end: 17.865,
                        confidence: 0.979138,
                        punctuated_word: "I've",
                      },
                      {
                        word: 'been',
                        start: 17.865,
                        end: 18.105,
                        confidence: 0.9998211,
                        punctuated_word: 'been',
                      },
                      {
                        word: 'here',
                        start: 18.105,
                        end: 18.345,
                        confidence: 0.9995721,
                        punctuated_word: 'here',
                      },
                      {
                        word: 'for',
                        start: 18.345,
                        end: 18.664999,
                        confidence: 0.9974909,
                        punctuated_word: 'for',
                      },
                      {
                        word: 'over',
                        start: 18.664999,
                        end: 19.145,
                        confidence: 0.9945885,
                        punctuated_word: 'over',
                      },
                      {
                        word: 'four',
                        start: 19.145,
                        end: 19.645,
                        confidence: 0.9992329,
                        punctuated_word: 'four',
                      },
                      {
                        word: 'and',
                        start: 19.705,
                        end: 19.785,
                        confidence: 0.9929288,
                        punctuated_word: 'and',
                      },
                      {
                        word: 'a',
                        start: 19.785,
                        end: 20.025,
                        confidence: 0.9867345,
                        punctuated_word: 'a',
                      },
                      {
                        word: 'half',
                        start: 20.025,
                        end: 20.505,
                        confidence: 0.9996507,
                        punctuated_word: 'half',
                      },
                      {
                        word: 'billion',
                        start: 20.505,
                        end: 21.005,
                        confidence: 0.99751866,
                        punctuated_word: 'billion',
                      },
                      {
                        word: 'years',
                        start: 21.145,
                        end: 21.645,
                        confidence: 0.80607724,
                        punctuated_word: 'years.',
                      },
                      {
                        word: 'twenty',
                        start: 22.985,
                        end: 23.384998,
                        confidence: 0.9499618,
                        punctuated_word: 'Twenty',
                      },
                      {
                        word: 'two',
                        start: 23.384998,
                        end: 23.704998,
                        confidence: 0.9970662,
                        punctuated_word: 'two',
                      },
                      {
                        word: 'thousand',
                        start: 23.704998,
                        end: 24.204998,
                        confidence: 0.9929807,
                        punctuated_word: 'thousand',
                      },
                      {
                        word: 'five',
                        start: 24.825,
                        end: 25.224998,
                        confidence: 0.9306703,
                        punctuated_word: 'five',
                      },
                      {
                        word: 'hundred',
                        start: 25.224998,
                        end: 25.704998,
                        confidence: 0.99975353,
                        punctuated_word: 'hundred',
                      },
                      {
                        word: 'times',
                        start: 25.704998,
                        end: 26.204998,
                        confidence: 0.9990337,
                        punctuated_word: 'times',
                      },
                      {
                        word: 'longer',
                        start: 26.744999,
                        end: 27.244999,
                        confidence: 0.9983815,
                        punctuated_word: 'longer',
                      },
                      {
                        word: 'than',
                        start: 27.704998,
                        end: 28.025,
                        confidence: 0.9983197,
                        punctuated_word: 'than',
                      },
                      {
                        word: 'you',
                        start: 28.025,
                        end: 28.525,
                        confidence: 0.9978076,
                        punctuated_word: 'you.',
                      },
                      {
                        word: 'i',
                        start: 29.75,
                        end: 29.91,
                        confidence: 0.99143535,
                        punctuated_word: 'I',
                      },
                      {
                        word: "don't",
                        start: 29.91,
                        end: 30.15,
                        confidence: 0.9996357,
                        punctuated_word: "don't",
                      },
                      {
                        word: 'really',
                        start: 30.15,
                        end: 30.65,
                        confidence: 0.9992218,
                        punctuated_word: 'really',
                      },
                      {
                        word: 'need',
                        start: 30.71,
                        end: 31.21,
                        confidence: 0.9994578,
                        punctuated_word: 'need',
                      },
                      {
                        word: 'people',
                        start: 31.27,
                        end: 31.77,
                        confidence: 0.9577169,
                        punctuated_word: 'people,',
                      },
                      {
                        word: 'but',
                        start: 32.63,
                        end: 32.87,
                        confidence: 0.99783343,
                        punctuated_word: 'but',
                      },
                      {
                        word: 'people',
                        start: 32.87,
                        end: 33.37,
                        confidence: 0.9994955,
                        punctuated_word: 'people',
                      },
                      {
                        word: 'need',
                        start: 33.67,
                        end: 33.989998,
                        confidence: 0.9994678,
                        punctuated_word: 'need',
                      },
                      {
                        word: 'me',
                        start: 33.989998,
                        end: 34.489998,
                        confidence: 0.999055,
                        punctuated_word: 'me.',
                      },
                      {
                        word: 'yes',
                        start: 35.75,
                        end: 36.15,
                        confidence: 0.9175291,
                        punctuated_word: 'Yes,',
                      },
                      {
                        word: 'your',
                        start: 36.15,
                        end: 36.55,
                        confidence: 0.99281013,
                        punctuated_word: 'your',
                      },
                      {
                        word: 'future',
                        start: 36.55,
                        end: 37.03,
                        confidence: 0.99988425,
                        punctuated_word: 'future',
                      },
                      {
                        word: 'depends',
                        start: 37.03,
                        end: 37.43,
                        confidence: 0.9994929,
                        punctuated_word: 'depends',
                      },
                      {
                        word: 'on',
                        start: 37.43,
                        end: 37.67,
                        confidence: 0.99914944,
                        punctuated_word: 'on',
                      },
                      {
                        word: 'me',
                        start: 37.67,
                        end: 38.17,
                        confidence: 0.99493027,
                        punctuated_word: 'me.',
                      },
                      {
                        word: 'when',
                        start: 39.11,
                        end: 39.35,
                        confidence: 0.97084856,
                        punctuated_word: 'When',
                      },
                      {
                        word: 'i',
                        start: 39.35,
                        end: 39.59,
                        confidence: 0.99950767,
                        punctuated_word: 'I',
                      },
                      {
                        word: 'thrive',
                        start: 39.59,
                        end: 40.09,
                        confidence: 0.9971422,
                        punctuated_word: 'thrive,',
                      },
                      {
                        word: 'you',
                        start: 40.63,
                        end: 40.87,
                        confidence: 0.99955267,
                        punctuated_word: 'you',
                      },
                      {
                        word: 'thrive',
                        start: 40.87,
                        end: 41.37,
                        confidence: 0.99762547,
                        punctuated_word: 'thrive.',
                      },
                      {
                        word: 'when',
                        start: 43.115,
                        end: 43.515,
                        confidence: 0.9950642,
                        punctuated_word: 'When',
                      },
                      {
                        word: 'i',
                        start: 43.515,
                        end: 43.755,
                        confidence: 0.99957126,
                        punctuated_word: 'I',
                      },
                      {
                        word: 'falter',
                        start: 43.755,
                        end: 44.255,
                        confidence: 0.99969816,
                        punctuated_word: 'falter,',
                      },
                      {
                        word: 'you',
                        start: 45.115,
                        end: 45.355,
                        confidence: 0.9998505,
                        punctuated_word: 'you',
                      },
                      {
                        word: 'falter',
                        start: 45.355,
                        end: 45.855,
                        confidence: 0.80944127,
                        punctuated_word: 'falter.',
                      },
                      {
                        word: 'or',
                        start: 47.675,
                        end: 47.995,
                        confidence: 0.9534921,
                        punctuated_word: 'Or',
                      },
                      {
                        word: 'worse',
                        start: 47.995,
                        end: 48.495,
                        confidence: 0.9129868,
                        punctuated_word: 'worse.',
                      },
                      {
                        word: 'but',
                        start: 53.355,
                        end: 53.675,
                        confidence: 0.7401629,
                        punctuated_word: 'But',
                      },
                      {
                        word: "i've",
                        start: 53.675,
                        end: 53.835,
                        confidence: 0.9772358,
                        punctuated_word: "I've",
                      },
                      {
                        word: 'been',
                        start: 53.835,
                        end: 54.075,
                        confidence: 0.9998578,
                        punctuated_word: 'been',
                      },
                      {
                        word: 'here',
                        start: 54.075,
                        end: 54.395,
                        confidence: 0.99967325,
                        punctuated_word: 'here',
                      },
                      {
                        word: 'for',
                        start: 54.395,
                        end: 54.555,
                        confidence: 0.9990746,
                        punctuated_word: 'for',
                      },
                      {
                        word: 'eons',
                        start: 54.555,
                        end: 55.055,
                        confidence: 0.9503066,
                        punctuated_word: 'eons.',
                      },
                      {
                        word: 'i',
                        start: 55.95,
                        end: 56.11,
                        confidence: 0.99804187,
                        punctuated_word: 'I',
                      },
                      {
                        word: 'have',
                        start: 56.11,
                        end: 56.43,
                        confidence: 0.9996909,
                        punctuated_word: 'have',
                      },
                      {
                        word: 'fed',
                        start: 56.43,
                        end: 56.829998,
                        confidence: 0.9981229,
                        punctuated_word: 'fed',
                      },
                      {
                        word: 'species',
                        start: 56.829998,
                        end: 57.329998,
                        confidence: 0.9999074,
                        punctuated_word: 'species',
                      },
                      {
                        word: 'greater',
                        start: 57.55,
                        end: 57.79,
                        confidence: 0.9993856,
                        punctuated_word: 'greater',
                      },
                      {
                        word: 'than',
                        start: 57.79,
                        end: 58.11,
                        confidence: 0.99893767,
                        punctuated_word: 'than',
                      },
                      {
                        word: 'you',
                        start: 58.11,
                        end: 58.61,
                        confidence: 0.9236101,
                        punctuated_word: 'you,',
                      },
                      {
                        word: 'and',
                        start: 58.75,
                        end: 58.989998,
                        confidence: 0.99876,
                        punctuated_word: 'and',
                      },
                      {
                        word: 'i',
                        start: 58.989998,
                        end: 59.149998,
                        confidence: 0.9992913,
                        punctuated_word: 'I',
                      },
                      {
                        word: 'have',
                        start: 59.149998,
                        end: 59.55,
                        confidence: 0.99945754,
                        punctuated_word: 'have',
                      },
                      {
                        word: 'starved',
                        start: 59.55,
                        end: 60.05,
                        confidence: 0.99984086,
                        punctuated_word: 'starved',
                      },
                      {
                        word: 'species',
                        start: 60.51,
                        end: 61.01,
                        confidence: 0.9998431,
                        punctuated_word: 'species',
                      },
                      {
                        word: 'greater',
                        start: 61.39,
                        end: 61.87,
                        confidence: 0.999491,
                        punctuated_word: 'greater',
                      },
                      {
                        word: 'than',
                        start: 61.87,
                        end: 62.11,
                        confidence: 0.9980313,
                        punctuated_word: 'than',
                      },
                      {
                        word: 'you',
                        start: 62.11,
                        end: 62.61,
                        confidence: 0.9699242,
                        punctuated_word: 'you.',
                      },
                      {
                        word: 'my',
                        start: 64.67,
                        end: 65.17,
                        confidence: 0.87121737,
                        punctuated_word: 'My',
                      },
                      {
                        word: 'oceans',
                        start: 65.229996,
                        end: 65.729996,
                        confidence: 0.93264604,
                        punctuated_word: 'oceans,',
                      },
                      {
                        word: 'my',
                        start: 67.229996,
                        end: 67.729996,
                        confidence: 0.99881965,
                        punctuated_word: 'my',
                      },
                      {
                        word: 'soil',
                        start: 67.869995,
                        end: 68.369995,
                        confidence: 0.9992186,
                        punctuated_word: 'soil,',
                      },
                      {
                        word: 'my',
                        start: 70.08501,
                        end: 70.485,
                        confidence: 0.9998927,
                        punctuated_word: 'my',
                      },
                      {
                        word: 'flowing',
                        start: 70.485,
                        end: 70.985,
                        confidence: 0.99985445,
                        punctuated_word: 'flowing',
                      },
                      {
                        word: 'streams',
                        start: 71.125,
                        end: 71.625,
                        confidence: 0.99916434,
                        punctuated_word: 'streams,',
                      },
                      {
                        word: 'my',
                        start: 71.845,
                        end: 72.345,
                        confidence: 0.9997296,
                        punctuated_word: 'my',
                      },
                      {
                        word: 'forests',
                        start: 72.565,
                        end: 73.065,
                        confidence: 0.7186612,
                        punctuated_word: 'forests,',
                      },
                      {
                        word: 'they',
                        start: 75.525,
                        end: 75.845,
                        confidence: 0.99564123,
                        punctuated_word: 'they',
                      },
                      {
                        word: 'all',
                        start: 75.845,
                        end: 76.345,
                        confidence: 0.9989538,
                        punctuated_word: 'all',
                      },
                      {
                        word: 'can',
                        start: 76.485,
                        end: 76.725006,
                        confidence: 0.9994252,
                        punctuated_word: 'can',
                      },
                      {
                        word: 'take',
                        start: 76.725006,
                        end: 76.965004,
                        confidence: 0.9997003,
                        punctuated_word: 'take',
                      },
                      {
                        word: 'you',
                        start: 76.965004,
                        end: 77.465004,
                        confidence: 0.99849784,
                        punctuated_word: 'you',
                      },
                      {
                        word: 'or',
                        start: 78.565,
                        end: 78.885,
                        confidence: 0.6025583,
                        punctuated_word: 'or',
                      },
                      {
                        word: 'leave',
                        start: 78.885,
                        end: 79.205,
                        confidence: 0.9998497,
                        punctuated_word: 'leave',
                      },
                      {
                        word: 'you',
                        start: 79.205,
                        end: 79.705,
                        confidence: 0.999208,
                        punctuated_word: 'you.',
                      },
                      {
                        word: 'how',
                        start: 81.590004,
                        end: 81.75,
                        confidence: 0.9674155,
                        punctuated_word: 'How',
                      },
                      {
                        word: 'you',
                        start: 81.75,
                        end: 81.990005,
                        confidence: 0.9996675,
                        punctuated_word: 'you',
                      },
                      {
                        word: 'choose',
                        start: 81.990005,
                        end: 82.39,
                        confidence: 0.9969708,
                        punctuated_word: 'choose',
                      },
                      {
                        word: 'to',
                        start: 82.39,
                        end: 82.55,
                        confidence: 0.9995819,
                        punctuated_word: 'to',
                      },
                      {
                        word: 'live',
                        start: 82.55,
                        end: 82.87,
                        confidence: 0.9996427,
                        punctuated_word: 'live',
                      },
                      {
                        word: 'each',
                        start: 82.87,
                        end: 83.11,
                        confidence: 0.99965763,
                        punctuated_word: 'each',
                      },
                      {
                        word: 'day',
                        start: 83.11,
                        end: 83.51,
                        confidence: 0.9406377,
                        punctuated_word: 'day,',
                      },
                      {
                        word: 'whether',
                        start: 83.51,
                        end: 83.91,
                        confidence: 0.99948186,
                        punctuated_word: 'whether',
                      },
                      {
                        word: 'you',
                        start: 83.91,
                        end: 84.15,
                        confidence: 0.99881077,
                        punctuated_word: 'you',
                      },
                      {
                        word: 'regard',
                        start: 84.15,
                        end: 84.65,
                        confidence: 0.99952066,
                        punctuated_word: 'regard',
                      },
                      {
                        word: 'or',
                        start: 84.87,
                        end: 85.19,
                        confidence: 0.9701967,
                        punctuated_word: 'or',
                      },
                      {
                        word: 'disregard',
                        start: 85.19,
                        end: 85.69,
                        confidence: 0.99937004,
                        punctuated_word: 'disregard',
                      },
                      {
                        word: 'me',
                        start: 85.83,
                        end: 86.310005,
                        confidence: 0.9628593,
                        punctuated_word: 'me,',
                      },
                      {
                        word: "doesn't",
                        start: 86.310005,
                        end: 86.630005,
                        confidence: 0.9989412,
                        punctuated_word: "doesn't",
                      },
                      {
                        word: 'really',
                        start: 86.630005,
                        end: 87.03,
                        confidence: 0.9990075,
                        punctuated_word: 'really',
                      },
                      {
                        word: 'matter',
                        start: 87.03,
                        end: 87.43,
                        confidence: 0.9996481,
                        punctuated_word: 'matter',
                      },
                      {
                        word: 'to',
                        start: 87.43,
                        end: 87.590004,
                        confidence: 0.9984665,
                        punctuated_word: 'to',
                      },
                      {
                        word: 'me',
                        start: 87.590004,
                        end: 88.090004,
                        confidence: 0.7814448,
                        punctuated_word: 'me,',
                      },
                      {
                        word: 'one',
                        start: 89.35,
                        end: 89.590004,
                        confidence: 0.99794704,
                        punctuated_word: 'one',
                      },
                      {
                        word: 'way',
                        start: 89.590004,
                        end: 90.090004,
                        confidence: 0.99978393,
                        punctuated_word: 'way',
                      },
                      {
                        word: 'or',
                        start: 90.630005,
                        end: 90.87,
                        confidence: 0.9622462,
                        punctuated_word: 'or',
                      },
                      {
                        word: 'the',
                        start: 90.87,
                        end: 91.03,
                        confidence: 0.9987349,
                        punctuated_word: 'the',
                      },
                      {
                        word: 'other',
                        start: 91.03,
                        end: 91.53,
                        confidence: 0.9965701,
                        punctuated_word: 'other.',
                      },
                      {
                        word: 'your',
                        start: 91.83,
                        end: 92.15,
                        confidence: 0.9331712,
                        punctuated_word: 'Your',
                      },
                      {
                        word: 'actions',
                        start: 92.15,
                        end: 92.65,
                        confidence: 0.999446,
                        punctuated_word: 'actions',
                      },
                      {
                        word: 'will',
                        start: 92.87,
                        end: 93.19,
                        confidence: 0.9986205,
                        punctuated_word: 'will',
                      },
                      {
                        word: 'determine',
                        start: 93.19,
                        end: 93.69,
                        confidence: 0.9998259,
                        punctuated_word: 'determine',
                      },
                      {
                        word: 'your',
                        start: 94.07,
                        end: 94.39,
                        confidence: 0.99888176,
                        punctuated_word: 'your',
                      },
                      {
                        word: 'fate',
                        start: 94.39,
                        end: 94.89,
                        confidence: 0.9739524,
                        punctuated_word: 'fate,',
                      },
                      {
                        word: 'not',
                        start: 95.235,
                        end: 95.475006,
                        confidence: 0.9996612,
                        punctuated_word: 'not',
                      },
                      {
                        word: 'mine',
                        start: 95.475006,
                        end: 95.975006,
                        confidence: 0.99792373,
                        punctuated_word: 'mine.',
                      },
                      {
                        word: 'i',
                        start: 96.195,
                        end: 96.435005,
                        confidence: 0.9644985,
                        punctuated_word: 'I',
                      },
                      {
                        word: 'am',
                        start: 96.435005,
                        end: 96.675,
                        confidence: 0.99927884,
                        punctuated_word: 'am',
                      },
                      {
                        word: 'nature',
                        start: 96.675,
                        end: 97.175,
                        confidence: 0.95485514,
                        punctuated_word: 'nature.',
                      },
                      {
                        word: 'i',
                        start: 97.315,
                        end: 97.555,
                        confidence: 0.9971111,
                        punctuated_word: 'I',
                      },
                      {
                        word: 'will',
                        start: 97.555,
                        end: 97.795006,
                        confidence: 0.99968433,
                        punctuated_word: 'will',
                      },
                      {
                        word: 'go',
                        start: 97.795006,
                        end: 97.955,
                        confidence: 0.9999013,
                        punctuated_word: 'go',
                      },
                      {
                        word: 'on',
                        start: 97.955,
                        end: 98.455,
                        confidence: 0.9968238,
                        punctuated_word: 'on.',
                      },
                      {
                        word: 'i',
                        start: 98.675,
                        end: 99.175,
                        confidence: 0.99300176,
                        punctuated_word: 'I',
                      },
                      {
                        word: 'am',
                        start: 99.235,
                        end: 99.635,
                        confidence: 0.998757,
                        punctuated_word: 'am',
                      },
                      {
                        word: 'prepared',
                        start: 99.635,
                        end: 100.135,
                        confidence: 0.99971336,
                        punctuated_word: 'prepared',
                      },
                      {
                        word: 'to',
                        start: 100.595,
                        end: 100.915,
                        confidence: 0.9995726,
                        punctuated_word: 'to',
                      },
                      {
                        word: 'evolve',
                        start: 100.915,
                        end: 101.415,
                        confidence: 0.99637693,
                        punctuated_word: 'evolve.',
                      },
                      {
                        word: 'are',
                        start: 104.435005,
                        end: 104.675,
                        confidence: 0.94356596,
                        punctuated_word: 'Are',
                      },
                      {
                        word: 'you',
                        start: 104.675,
                        end: 105.175,
                        confidence: 0.999007,
                        punctuated_word: 'you?',
                      },
                    ],
                  },
                ],
              },
            ],
            utterances: [
              {
                start: 3.84,
                end: 5.14,
                confidence: 0.91813684,
                channel: 0,
                transcript: 'Some call me nature.',
                words: [
                  {
                    word: 'some',
                    start: 3.84,
                    end: 4.16,
                    confidence: 0.82021403,
                    punctuated_word: 'Some',
                  },
                  {
                    word: 'call',
                    start: 4.16,
                    end: 4.4,
                    confidence: 0.9992494,
                    punctuated_word: 'call',
                  },
                  {
                    word: 'me',
                    start: 4.4,
                    end: 4.64,
                    confidence: 0.99974924,
                    punctuated_word: 'me',
                  },
                  {
                    word: 'nature',
                    start: 4.64,
                    end: 5.14,
                    confidence: 0.85333455,
                    punctuated_word: 'nature.',
                  },
                ],
                id: '75b07fc3-2f84-43eb-8f7b-d66225af0791',
              },
              {
                start: 11.5199995,
                end: 12.82,
                confidence: 0.9866436,
                channel: 0,
                transcript: 'Others call me',
                words: [
                  {
                    word: 'others',
                    start: 11.5199995,
                    end: 12,
                    confidence: 0.9610789,
                    punctuated_word: 'Others',
                  },
                  {
                    word: 'call',
                    start: 12,
                    end: 12.32,
                    confidence: 0.99918526,
                    punctuated_word: 'call',
                  },
                  {
                    word: 'me',
                    start: 12.32,
                    end: 12.82,
                    confidence: 0.9996667,
                    punctuated_word: 'me',
                  },
                ],
                id: '8a5a9f35-93ae-4093-9829-3232e30fa73b',
              },
              {
                start: 13.36,
                end: 13.86,
                confidence: 0.61809415,
                channel: 0,
                transcript: 'mother',
                words: [
                  {
                    word: 'mother',
                    start: 13.36,
                    end: 13.86,
                    confidence: 0.61809415,
                    punctuated_word: 'mother',
                  },
                ],
                id: '9720f82e-7d02-4bbb-92c8-a2115aa10af1',
              },
              {
                start: 14.184999,
                end: 14.684999,
                confidence: 0.99900067,
                channel: 0,
                transcript: 'nature.',
                words: [
                  {
                    word: 'nature',
                    start: 14.184999,
                    end: 14.684999,
                    confidence: 0.99900067,
                    punctuated_word: 'nature.',
                  },
                ],
                id: '49ea148d-634f-4dd2-8d26-a9dc3d62be74',
              },
              {
                start: 17.465,
                end: 21.645,
                confidence: 0.977523,
                channel: 0,
                transcript:
                  "I've been here for over four and a half billion years.",
                words: [
                  {
                    word: "i've",
                    start: 17.465,
                    end: 17.865,
                    confidence: 0.979138,
                    punctuated_word: "I've",
                  },
                  {
                    word: 'been',
                    start: 17.865,
                    end: 18.105,
                    confidence: 0.9998211,
                    punctuated_word: 'been',
                  },
                  {
                    word: 'here',
                    start: 18.105,
                    end: 18.345,
                    confidence: 0.9995721,
                    punctuated_word: 'here',
                  },
                  {
                    word: 'for',
                    start: 18.345,
                    end: 18.664999,
                    confidence: 0.9974909,
                    punctuated_word: 'for',
                  },
                  {
                    word: 'over',
                    start: 18.664999,
                    end: 19.145,
                    confidence: 0.9945885,
                    punctuated_word: 'over',
                  },
                  {
                    word: 'four',
                    start: 19.145,
                    end: 19.645,
                    confidence: 0.9992329,
                    punctuated_word: 'four',
                  },
                  {
                    word: 'and',
                    start: 19.705,
                    end: 19.785,
                    confidence: 0.9929288,
                    punctuated_word: 'and',
                  },
                  {
                    word: 'a',
                    start: 19.785,
                    end: 20.025,
                    confidence: 0.9867345,
                    punctuated_word: 'a',
                  },
                  {
                    word: 'half',
                    start: 20.025,
                    end: 20.505,
                    confidence: 0.9996507,
                    punctuated_word: 'half',
                  },
                  {
                    word: 'billion',
                    start: 20.505,
                    end: 21.005,
                    confidence: 0.99751866,
                    punctuated_word: 'billion',
                  },
                  {
                    word: 'years',
                    start: 21.145,
                    end: 21.645,
                    confidence: 0.80607724,
                    punctuated_word: 'years.',
                  },
                ],
                id: '6304f003-e87a-4d19-b1ac-ce41ab7898e7',
              },
              {
                start: 22.985,
                end: 24.204998,
                confidence: 0.9800029,
                channel: 0,
                transcript: 'Twenty two thousand',
                words: [
                  {
                    word: 'twenty',
                    start: 22.985,
                    end: 23.384998,
                    confidence: 0.9499618,
                    punctuated_word: 'Twenty',
                  },
                  {
                    word: 'two',
                    start: 23.384998,
                    end: 23.704998,
                    confidence: 0.9970662,
                    punctuated_word: 'two',
                  },
                  {
                    word: 'thousand',
                    start: 23.704998,
                    end: 24.204998,
                    confidence: 0.9929807,
                    punctuated_word: 'thousand',
                  },
                ],
                id: '564db594-6c1f-4af7-b24a-d0e4fe5602be',
              },
              {
                start: 24.825,
                end: 26.204998,
                confidence: 0.9764859,
                channel: 0,
                transcript: 'five hundred times',
                words: [
                  {
                    word: 'five',
                    start: 24.825,
                    end: 25.224998,
                    confidence: 0.9306703,
                    punctuated_word: 'five',
                  },
                  {
                    word: 'hundred',
                    start: 25.224998,
                    end: 25.704998,
                    confidence: 0.99975353,
                    punctuated_word: 'hundred',
                  },
                  {
                    word: 'times',
                    start: 25.704998,
                    end: 26.204998,
                    confidence: 0.9990337,
                    punctuated_word: 'times',
                  },
                ],
                id: '1756601e-9921-40e0-b10d-899a75439650',
              },
              {
                start: 26.744999,
                end: 27.244999,
                confidence: 0.9983815,
                channel: 0,
                transcript: 'longer',
                words: [
                  {
                    word: 'longer',
                    start: 26.744999,
                    end: 27.244999,
                    confidence: 0.9983815,
                    punctuated_word: 'longer',
                  },
                ],
                id: '28559d33-00b2-4532-9443-872426e20c87',
              },
              {
                start: 27.704998,
                end: 28.525,
                confidence: 0.9980637,
                channel: 0,
                transcript: 'than you.',
                words: [
                  {
                    word: 'than',
                    start: 27.704998,
                    end: 28.025,
                    confidence: 0.9983197,
                    punctuated_word: 'than',
                  },
                  {
                    word: 'you',
                    start: 28.025,
                    end: 28.525,
                    confidence: 0.9978076,
                    punctuated_word: 'you.',
                  },
                ],
                id: '7318fc19-ce7b-4cda-a52b-e67135984ae3',
              },
              {
                start: 29.75,
                end: 31.77,
                confidence: 0.9894935,
                channel: 0,
                transcript: "I don't really need people,",
                words: [
                  {
                    word: 'i',
                    start: 29.75,
                    end: 29.91,
                    confidence: 0.99143535,
                    punctuated_word: 'I',
                  },
                  {
                    word: "don't",
                    start: 29.91,
                    end: 30.15,
                    confidence: 0.9996357,
                    punctuated_word: "don't",
                  },
                  {
                    word: 'really',
                    start: 30.15,
                    end: 30.65,
                    confidence: 0.9992218,
                    punctuated_word: 'really',
                  },
                  {
                    word: 'need',
                    start: 30.71,
                    end: 31.21,
                    confidence: 0.9994578,
                    punctuated_word: 'need',
                  },
                  {
                    word: 'people',
                    start: 31.27,
                    end: 31.77,
                    confidence: 0.9577169,
                    punctuated_word: 'people,',
                  },
                ],
                id: '6614d961-de70-4ca0-84b2-b0e38db291e5',
              },
              {
                start: 32.63,
                end: 34.489998,
                confidence: 0.998963,
                channel: 0,
                transcript: 'but people need me.',
                words: [
                  {
                    word: 'but',
                    start: 32.63,
                    end: 32.87,
                    confidence: 0.99783343,
                    punctuated_word: 'but',
                  },
                  {
                    word: 'people',
                    start: 32.87,
                    end: 33.37,
                    confidence: 0.9994955,
                    punctuated_word: 'people',
                  },
                  {
                    word: 'need',
                    start: 33.67,
                    end: 33.989998,
                    confidence: 0.9994678,
                    punctuated_word: 'need',
                  },
                  {
                    word: 'me',
                    start: 33.989998,
                    end: 34.489998,
                    confidence: 0.999055,
                    punctuated_word: 'me.',
                  },
                ],
                id: '50f44022-da92-48b4-b350-badf119626c0',
              },
              {
                start: 35.75,
                end: 38.17,
                confidence: 0.98396605,
                channel: 0,
                transcript: 'Yes, your future depends on me.',
                words: [
                  {
                    word: 'yes',
                    start: 35.75,
                    end: 36.15,
                    confidence: 0.9175291,
                    punctuated_word: 'Yes,',
                  },
                  {
                    word: 'your',
                    start: 36.15,
                    end: 36.55,
                    confidence: 0.99281013,
                    punctuated_word: 'your',
                  },
                  {
                    word: 'future',
                    start: 36.55,
                    end: 37.03,
                    confidence: 0.99988425,
                    punctuated_word: 'future',
                  },
                  {
                    word: 'depends',
                    start: 37.03,
                    end: 37.43,
                    confidence: 0.9994929,
                    punctuated_word: 'depends',
                  },
                  {
                    word: 'on',
                    start: 37.43,
                    end: 37.67,
                    confidence: 0.99914944,
                    punctuated_word: 'on',
                  },
                  {
                    word: 'me',
                    start: 37.67,
                    end: 38.17,
                    confidence: 0.99493027,
                    punctuated_word: 'me.',
                  },
                ],
                id: '6314877e-b236-4094-9b9b-938fdd0e49d1',
              },
              {
                start: 39.11,
                end: 40.09,
                confidence: 0.9891661,
                channel: 0,
                transcript: 'When I thrive,',
                words: [
                  {
                    word: 'when',
                    start: 39.11,
                    end: 39.35,
                    confidence: 0.97084856,
                    punctuated_word: 'When',
                  },
                  {
                    word: 'i',
                    start: 39.35,
                    end: 39.59,
                    confidence: 0.99950767,
                    punctuated_word: 'I',
                  },
                  {
                    word: 'thrive',
                    start: 39.59,
                    end: 40.09,
                    confidence: 0.9971422,
                    punctuated_word: 'thrive,',
                  },
                ],
                id: 'cff9fe4d-e4a0-494a-baca-1cff124af400',
              },
              {
                start: 40.63,
                end: 41.37,
                confidence: 0.99858904,
                channel: 0,
                transcript: 'you thrive.',
                words: [
                  {
                    word: 'you',
                    start: 40.63,
                    end: 40.87,
                    confidence: 0.99955267,
                    punctuated_word: 'you',
                  },
                  {
                    word: 'thrive',
                    start: 40.87,
                    end: 41.37,
                    confidence: 0.99762547,
                    punctuated_word: 'thrive.',
                  },
                ],
                id: '4187650d-d964-4efa-9dc9-42d7a6c42810',
              },
              {
                start: 43.115,
                end: 44.255,
                confidence: 0.99811125,
                channel: 0,
                transcript: 'When I falter,',
                words: [
                  {
                    word: 'when',
                    start: 43.115,
                    end: 43.515,
                    confidence: 0.9950642,
                    punctuated_word: 'When',
                  },
                  {
                    word: 'i',
                    start: 43.515,
                    end: 43.755,
                    confidence: 0.99957126,
                    punctuated_word: 'I',
                  },
                  {
                    word: 'falter',
                    start: 43.755,
                    end: 44.255,
                    confidence: 0.99969816,
                    punctuated_word: 'falter,',
                  },
                ],
                id: '1a8f1157-2ad8-42f8-b7d7-db481aeeb1ed',
              },
              {
                start: 45.115,
                end: 45.855,
                confidence: 0.9046459,
                channel: 0,
                transcript: 'you falter.',
                words: [
                  {
                    word: 'you',
                    start: 45.115,
                    end: 45.355,
                    confidence: 0.9998505,
                    punctuated_word: 'you',
                  },
                  {
                    word: 'falter',
                    start: 45.355,
                    end: 45.855,
                    confidence: 0.80944127,
                    punctuated_word: 'falter.',
                  },
                ],
                id: '38aefb53-069c-4477-9eac-9e272f93dda0',
              },
              {
                start: 47.675,
                end: 48.495,
                confidence: 0.93323946,
                channel: 0,
                transcript: 'Or worse.',
                words: [
                  {
                    word: 'or',
                    start: 47.675,
                    end: 47.995,
                    confidence: 0.9534921,
                    punctuated_word: 'Or',
                  },
                  {
                    word: 'worse',
                    start: 47.995,
                    end: 48.495,
                    confidence: 0.9129868,
                    punctuated_word: 'worse.',
                  },
                ],
                id: '86e117a9-7334-4b64-964e-a38a1741b9ac',
              },
              {
                start: 53.355,
                end: 55.055,
                confidence: 0.9443851,
                channel: 0,
                transcript: "But I've been here for eons.",
                words: [
                  {
                    word: 'but',
                    start: 53.355,
                    end: 53.675,
                    confidence: 0.7401629,
                    punctuated_word: 'But',
                  },
                  {
                    word: "i've",
                    start: 53.675,
                    end: 53.835,
                    confidence: 0.9772358,
                    punctuated_word: "I've",
                  },
                  {
                    word: 'been',
                    start: 53.835,
                    end: 54.075,
                    confidence: 0.9998578,
                    punctuated_word: 'been',
                  },
                  {
                    word: 'here',
                    start: 54.075,
                    end: 54.395,
                    confidence: 0.99967325,
                    punctuated_word: 'here',
                  },
                  {
                    word: 'for',
                    start: 54.395,
                    end: 54.555,
                    confidence: 0.9990746,
                    punctuated_word: 'for',
                  },
                  {
                    word: 'eons',
                    start: 54.555,
                    end: 55.055,
                    confidence: 0.9503066,
                    punctuated_word: 'eons.',
                  },
                ],
                id: 'd82d210c-4a16-4c56-bb73-3a24e9779f05',
              },
              {
                start: 55.95,
                end: 60.05,
                confidence: 0.9922769,
                channel: 0,
                transcript:
                  'I have fed species greater than you, and I have starved',
                words: [
                  {
                    word: 'i',
                    start: 55.95,
                    end: 56.11,
                    confidence: 0.99804187,
                    punctuated_word: 'I',
                  },
                  {
                    word: 'have',
                    start: 56.11,
                    end: 56.43,
                    confidence: 0.9996909,
                    punctuated_word: 'have',
                  },
                  {
                    word: 'fed',
                    start: 56.43,
                    end: 56.829998,
                    confidence: 0.9981229,
                    punctuated_word: 'fed',
                  },
                  {
                    word: 'species',
                    start: 56.829998,
                    end: 57.329998,
                    confidence: 0.9999074,
                    punctuated_word: 'species',
                  },
                  {
                    word: 'greater',
                    start: 57.55,
                    end: 57.79,
                    confidence: 0.9993856,
                    punctuated_word: 'greater',
                  },
                  {
                    word: 'than',
                    start: 57.79,
                    end: 58.11,
                    confidence: 0.99893767,
                    punctuated_word: 'than',
                  },
                  {
                    word: 'you',
                    start: 58.11,
                    end: 58.61,
                    confidence: 0.9236101,
                    punctuated_word: 'you,',
                  },
                  {
                    word: 'and',
                    start: 58.75,
                    end: 58.989998,
                    confidence: 0.99876,
                    punctuated_word: 'and',
                  },
                  {
                    word: 'i',
                    start: 58.989998,
                    end: 59.149998,
                    confidence: 0.9992913,
                    punctuated_word: 'I',
                  },
                  {
                    word: 'have',
                    start: 59.149998,
                    end: 59.55,
                    confidence: 0.99945754,
                    punctuated_word: 'have',
                  },
                  {
                    word: 'starved',
                    start: 59.55,
                    end: 60.05,
                    confidence: 0.99984086,
                    punctuated_word: 'starved',
                  },
                ],
                id: 'd5bf236d-2d7d-42d4-86da-11178396370b',
              },
              {
                start: 60.51,
                end: 61.01,
                confidence: 0.9998431,
                channel: 0,
                transcript: 'species',
                words: [
                  {
                    word: 'species',
                    start: 60.51,
                    end: 61.01,
                    confidence: 0.9998431,
                    punctuated_word: 'species',
                  },
                ],
                id: 'b0e38043-8092-4df3-ae8e-11bda1ea8294',
              },
              {
                start: 61.39,
                end: 62.61,
                confidence: 0.98914886,
                channel: 0,
                transcript: 'greater than you.',
                words: [
                  {
                    word: 'greater',
                    start: 61.39,
                    end: 61.87,
                    confidence: 0.999491,
                    punctuated_word: 'greater',
                  },
                  {
                    word: 'than',
                    start: 61.87,
                    end: 62.11,
                    confidence: 0.9980313,
                    punctuated_word: 'than',
                  },
                  {
                    word: 'you',
                    start: 62.11,
                    end: 62.61,
                    confidence: 0.9699242,
                    punctuated_word: 'you.',
                  },
                ],
                id: '1e32511a-2cc2-475c-a87d-e1e38a104239',
              },
              {
                start: 64.67,
                end: 65.729996,
                confidence: 0.9019317,
                channel: 0,
                transcript: 'My oceans,',
                words: [
                  {
                    word: 'my',
                    start: 64.67,
                    end: 65.17,
                    confidence: 0.87121737,
                    punctuated_word: 'My',
                  },
                  {
                    word: 'oceans',
                    start: 65.229996,
                    end: 65.729996,
                    confidence: 0.93264604,
                    punctuated_word: 'oceans,',
                  },
                ],
                id: '9629162c-cff6-449f-af3b-c9a1094cc025',
              },
              {
                start: 67.229996,
                end: 68.369995,
                confidence: 0.99901915,
                channel: 0,
                transcript: 'my soil,',
                words: [
                  {
                    word: 'my',
                    start: 67.229996,
                    end: 67.729996,
                    confidence: 0.99881965,
                    punctuated_word: 'my',
                  },
                  {
                    word: 'soil',
                    start: 67.869995,
                    end: 68.369995,
                    confidence: 0.9992186,
                    punctuated_word: 'soil,',
                  },
                ],
                id: '1870c99d-5918-45ff-8c39-bdb3dc64f47a',
              },
              {
                start: 70.08501,
                end: 73.065,
                confidence: 0.94346046,
                channel: 0,
                transcript: 'my flowing streams, my forests,',
                words: [
                  {
                    word: 'my',
                    start: 70.08501,
                    end: 70.485,
                    confidence: 0.9998927,
                    punctuated_word: 'my',
                  },
                  {
                    word: 'flowing',
                    start: 70.485,
                    end: 70.985,
                    confidence: 0.99985445,
                    punctuated_word: 'flowing',
                  },
                  {
                    word: 'streams',
                    start: 71.125,
                    end: 71.625,
                    confidence: 0.99916434,
                    punctuated_word: 'streams,',
                  },
                  {
                    word: 'my',
                    start: 71.845,
                    end: 72.345,
                    confidence: 0.9997296,
                    punctuated_word: 'my',
                  },
                  {
                    word: 'forests',
                    start: 72.565,
                    end: 73.065,
                    confidence: 0.7186612,
                    punctuated_word: 'forests,',
                  },
                ],
                id: '8b2f256c-2b98-41c4-90e9-e35c5dd8ed30',
              },
              {
                start: 75.525,
                end: 77.465004,
                confidence: 0.9984437,
                channel: 0,
                transcript: 'they all can take you',
                words: [
                  {
                    word: 'they',
                    start: 75.525,
                    end: 75.845,
                    confidence: 0.99564123,
                    punctuated_word: 'they',
                  },
                  {
                    word: 'all',
                    start: 75.845,
                    end: 76.345,
                    confidence: 0.9989538,
                    punctuated_word: 'all',
                  },
                  {
                    word: 'can',
                    start: 76.485,
                    end: 76.725006,
                    confidence: 0.9994252,
                    punctuated_word: 'can',
                  },
                  {
                    word: 'take',
                    start: 76.725006,
                    end: 76.965004,
                    confidence: 0.9997003,
                    punctuated_word: 'take',
                  },
                  {
                    word: 'you',
                    start: 76.965004,
                    end: 77.465004,
                    confidence: 0.99849784,
                    punctuated_word: 'you',
                  },
                ],
                id: '2c6e54ea-7352-4ff5-9394-2ec73f2acdb3',
              },
              {
                start: 78.565,
                end: 79.705,
                confidence: 0.8672053,
                channel: 0,
                transcript: 'or leave you.',
                words: [
                  {
                    word: 'or',
                    start: 78.565,
                    end: 78.885,
                    confidence: 0.6025583,
                    punctuated_word: 'or',
                  },
                  {
                    word: 'leave',
                    start: 78.885,
                    end: 79.205,
                    confidence: 0.9998497,
                    punctuated_word: 'leave',
                  },
                  {
                    word: 'you',
                    start: 79.205,
                    end: 79.705,
                    confidence: 0.999208,
                    punctuated_word: 'you.',
                  },
                ],
                id: 'f78bcd9e-f683-4aee-aafe-fd0ea2cfc982',
              },
              {
                start: 81.590004,
                end: 88.090004,
                confidence: 0.97840667,
                channel: 0,
                transcript:
                  "How you choose to live each day, whether you regard or disregard me, doesn't really matter to me,",
                words: [
                  {
                    word: 'how',
                    start: 81.590004,
                    end: 81.75,
                    confidence: 0.9674155,
                    punctuated_word: 'How',
                  },
                  {
                    word: 'you',
                    start: 81.75,
                    end: 81.990005,
                    confidence: 0.9996675,
                    punctuated_word: 'you',
                  },
                  {
                    word: 'choose',
                    start: 81.990005,
                    end: 82.39,
                    confidence: 0.9969708,
                    punctuated_word: 'choose',
                  },
                  {
                    word: 'to',
                    start: 82.39,
                    end: 82.55,
                    confidence: 0.9995819,
                    punctuated_word: 'to',
                  },
                  {
                    word: 'live',
                    start: 82.55,
                    end: 82.87,
                    confidence: 0.9996427,
                    punctuated_word: 'live',
                  },
                  {
                    word: 'each',
                    start: 82.87,
                    end: 83.11,
                    confidence: 0.99965763,
                    punctuated_word: 'each',
                  },
                  {
                    word: 'day',
                    start: 83.11,
                    end: 83.51,
                    confidence: 0.9406377,
                    punctuated_word: 'day,',
                  },
                  {
                    word: 'whether',
                    start: 83.51,
                    end: 83.91,
                    confidence: 0.99948186,
                    punctuated_word: 'whether',
                  },
                  {
                    word: 'you',
                    start: 83.91,
                    end: 84.15,
                    confidence: 0.99881077,
                    punctuated_word: 'you',
                  },
                  {
                    word: 'regard',
                    start: 84.15,
                    end: 84.65,
                    confidence: 0.99952066,
                    punctuated_word: 'regard',
                  },
                  {
                    word: 'or',
                    start: 84.87,
                    end: 85.19,
                    confidence: 0.9701967,
                    punctuated_word: 'or',
                  },
                  {
                    word: 'disregard',
                    start: 85.19,
                    end: 85.69,
                    confidence: 0.99937004,
                    punctuated_word: 'disregard',
                  },
                  {
                    word: 'me',
                    start: 85.83,
                    end: 86.310005,
                    confidence: 0.9628593,
                    punctuated_word: 'me,',
                  },
                  {
                    word: "doesn't",
                    start: 86.310005,
                    end: 86.630005,
                    confidence: 0.9989412,
                    punctuated_word: "doesn't",
                  },
                  {
                    word: 'really',
                    start: 86.630005,
                    end: 87.03,
                    confidence: 0.9990075,
                    punctuated_word: 'really',
                  },
                  {
                    word: 'matter',
                    start: 87.03,
                    end: 87.43,
                    confidence: 0.9996481,
                    punctuated_word: 'matter',
                  },
                  {
                    word: 'to',
                    start: 87.43,
                    end: 87.590004,
                    confidence: 0.9984665,
                    punctuated_word: 'to',
                  },
                  {
                    word: 'me',
                    start: 87.590004,
                    end: 88.090004,
                    confidence: 0.7814448,
                    punctuated_word: 'me,',
                  },
                ],
                id: '92a8a823-b1c2-4b45-8212-316a7c926992',
              },
              {
                start: 89.35,
                end: 90.090004,
                confidence: 0.9988655,
                channel: 0,
                transcript: 'one way',
                words: [
                  {
                    word: 'one',
                    start: 89.35,
                    end: 89.590004,
                    confidence: 0.99794704,
                    punctuated_word: 'one',
                  },
                  {
                    word: 'way',
                    start: 89.590004,
                    end: 90.090004,
                    confidence: 0.99978393,
                    punctuated_word: 'way',
                  },
                ],
                id: 'c4438f00-c71b-4896-a77f-22d51c075a13',
              },
              {
                start: 90.630005,
                end: 91.53,
                confidence: 0.9858504,
                channel: 0,
                transcript: 'or the other.',
                words: [
                  {
                    word: 'or',
                    start: 90.630005,
                    end: 90.87,
                    confidence: 0.9622462,
                    punctuated_word: 'or',
                  },
                  {
                    word: 'the',
                    start: 90.87,
                    end: 91.03,
                    confidence: 0.9987349,
                    punctuated_word: 'the',
                  },
                  {
                    word: 'other',
                    start: 91.03,
                    end: 91.53,
                    confidence: 0.9965701,
                    punctuated_word: 'other.',
                  },
                ],
                id: '6e7986e3-d1e5-425f-8800-7a1bf55d8c7a',
              },
              {
                start: 91.83,
                end: 93.69,
                confidence: 0.9827659,
                channel: 0,
                transcript: 'Your actions will determine',
                words: [
                  {
                    word: 'your',
                    start: 91.83,
                    end: 92.15,
                    confidence: 0.9331712,
                    punctuated_word: 'Your',
                  },
                  {
                    word: 'actions',
                    start: 92.15,
                    end: 92.65,
                    confidence: 0.999446,
                    punctuated_word: 'actions',
                  },
                  {
                    word: 'will',
                    start: 92.87,
                    end: 93.19,
                    confidence: 0.9986205,
                    punctuated_word: 'will',
                  },
                  {
                    word: 'determine',
                    start: 93.19,
                    end: 93.69,
                    confidence: 0.9998259,
                    punctuated_word: 'determine',
                  },
                ],
                id: 'bcdd8bbb-ea10-4960-90cb-02d2f84ada31',
              },
              {
                start: 94.07,
                end: 94.89,
                confidence: 0.98641706,
                channel: 0,
                transcript: 'your fate,',
                words: [
                  {
                    word: 'your',
                    start: 94.07,
                    end: 94.39,
                    confidence: 0.99888176,
                    punctuated_word: 'your',
                  },
                  {
                    word: 'fate',
                    start: 94.39,
                    end: 94.89,
                    confidence: 0.9739524,
                    punctuated_word: 'fate,',
                  },
                ],
                id: 'ab29089f-2e76-45c0-87c2-03620a5cb381',
              },
              {
                start: 95.235,
                end: 100.135,
                confidence: 0.99176747,
                channel: 0,
                transcript:
                  'not mine. I am nature. I will go on. I am prepared',
                words: [
                  {
                    word: 'not',
                    start: 95.235,
                    end: 95.475006,
                    confidence: 0.9996612,
                    punctuated_word: 'not',
                  },
                  {
                    word: 'mine',
                    start: 95.475006,
                    end: 95.975006,
                    confidence: 0.99792373,
                    punctuated_word: 'mine.',
                  },
                  {
                    word: 'i',
                    start: 96.195,
                    end: 96.435005,
                    confidence: 0.9644985,
                    punctuated_word: 'I',
                  },
                  {
                    word: 'am',
                    start: 96.435005,
                    end: 96.675,
                    confidence: 0.99927884,
                    punctuated_word: 'am',
                  },
                  {
                    word: 'nature',
                    start: 96.675,
                    end: 97.175,
                    confidence: 0.95485514,
                    punctuated_word: 'nature.',
                  },
                  {
                    word: 'i',
                    start: 97.315,
                    end: 97.555,
                    confidence: 0.9971111,
                    punctuated_word: 'I',
                  },
                  {
                    word: 'will',
                    start: 97.555,
                    end: 97.795006,
                    confidence: 0.99968433,
                    punctuated_word: 'will',
                  },
                  {
                    word: 'go',
                    start: 97.795006,
                    end: 97.955,
                    confidence: 0.9999013,
                    punctuated_word: 'go',
                  },
                  {
                    word: 'on',
                    start: 97.955,
                    end: 98.455,
                    confidence: 0.9968238,
                    punctuated_word: 'on.',
                  },
                  {
                    word: 'i',
                    start: 98.675,
                    end: 99.175,
                    confidence: 0.99300176,
                    punctuated_word: 'I',
                  },
                  {
                    word: 'am',
                    start: 99.235,
                    end: 99.635,
                    confidence: 0.998757,
                    punctuated_word: 'am',
                  },
                  {
                    word: 'prepared',
                    start: 99.635,
                    end: 100.135,
                    confidence: 0.99971336,
                    punctuated_word: 'prepared',
                  },
                ],
                id: 'ae73bbc1-ce7a-40f1-a041-558d3ffb2ebb',
              },
              {
                start: 100.595,
                end: 101.415,
                confidence: 0.99797475,
                channel: 0,
                transcript: 'to evolve.',
                words: [
                  {
                    word: 'to',
                    start: 100.595,
                    end: 100.915,
                    confidence: 0.9995726,
                    punctuated_word: 'to',
                  },
                  {
                    word: 'evolve',
                    start: 100.915,
                    end: 101.415,
                    confidence: 0.99637693,
                    punctuated_word: 'evolve.',
                  },
                ],
                id: '965cfdd5-985a-41ca-b3db-1292dbea34db',
              },
              {
                start: 104.435005,
                end: 105.175,
                confidence: 0.9712865,
                channel: 0,
                transcript: 'Are you?',
                words: [
                  {
                    word: 'are',
                    start: 104.435005,
                    end: 104.675,
                    confidence: 0.94356596,
                    punctuated_word: 'Are',
                  },
                  {
                    word: 'you',
                    start: 104.675,
                    end: 105.175,
                    confidence: 0.999007,
                    punctuated_word: 'you?',
                  },
                ],
                id: 'd9ffa29b-c074-4999-9a3b-0929dc82af89',
              },
            ],
          },
        },
      };

      if (error) {
        console.error(
          `[DeepgramTranscriptionService] Deepgram API error:`,
          error,
        );
        throw new Error(`Deepgram transcription failed: ${error.message}`);
      }
      if (!result) {
        throw new Error('Deepgram transcription returned no result.');
      }

      console.log(
        `[DeepgramTranscriptionService] Transcription received from Deepgram.`,
      );
      this.emit('progress', 100);
      return result;
    } catch (err: any) {
      console.error(
        `[DeepgramTranscriptionService] Error during transcription:`,
        err,
      );
      throw new Error(`Failed to transcribe audio: ${err.message || err}`);
    }
  }
}
