import { Poppins } from 'next/font/google';

import type { Metadata } from 'next';

import '@/styles/global.scss';

import { cookies } from 'next/headers';
import { forbidden, unauthorized } from 'next/navigation';

import { Toaster } from '@/admin/components/ui/sonner';
import { AuthProvider } from '@/context/auth-provider';
import { BannerProvider } from '@/context/banner-context';
import { TokenService } from '@monorepo/token';

const inter = Poppins({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get('accessToken');

  if (!token) return forbidden();

  const tokenService = new TokenService(process.env.JWT_SECRET!);
  const isAdmin = tokenService.isUserAdmin(token.value);

  if (!isAdmin) return unauthorized();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <BannerProvider>{children}</BannerProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
