import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import '@/styles/global.scss';

import { AuthProvider } from '@/context/auth-context';
import { BannerProvider } from '@/context/banner-context';
import { Toaster } from '@/admin/components/ui/sonner';


const inter = Poppins({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <BannerProvider>{children}</BannerProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
