export const tempOutput = {
  subtitles: {
    hi: [
      {
        endTimecode: '0:05',
        startTimecode: '0:03',
        text: 'कुछ लोग मुझे प्रकृति कहते हैं।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:15',
        startTimecode: '0:11',
        text: 'दूसरे मुझे प्रकृति माता कहते हैं।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:26',
        startTimecode: '0:16',
        text: 'मैं यहाँ साढ़े चार अरब साल से हूँ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:28',
        startTimecode: '0:26',
        text: 'तुम्हारे मुकाबले 22,500 गुना ज्यादा लम्बा।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:32',
        startTimecode: '0:29',
        text: 'मुझे लोगों की वाकई जरूरत नहीं है।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:35',
        startTimecode: '0:32',
        text: 'लेकिन लोगों को मेरी जरूरत है।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:38',
        startTimecode: '0:36',
        text: 'हाँ, तुम्हारा भविष्य मुझ पर निर्भर है।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:41',
        startTimecode: '0:38',
        text: 'जब मैं फलती फूलती हूँ, तो तुम फलते फूलते हो।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:51',
        startTimecode: '0:43',
        text: 'जब मैं डगमगाती हूँ, तो तुम डगमगाते हो।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:51',
        startTimecode: '0:51',
        text: 'या बदतर।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:58',
        startTimecode: '0:53',
        text: 'लेकिन मैं तो सदियों से यहाँ हूँ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:03',
        startTimecode: '0:58',
        text: 'मैंने तुमसे महानतर प्रजातियों को खाना खिलाया है, और मैंने तुमसे महानतर प्रजातियों को भूखा रखा है।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:06',
        startTimecode: '1:04',
        text: 'मेरे महासागर।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:08',
        startTimecode: '1:07',
        text: 'मेरी मिट्टी।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:11',
        startTimecode: '1:09',
        text: 'मेरी बहती धाराएँ, मेरे जंगल।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:20',
        startTimecode: '1:16',
        text: 'वे सब तुम्हें ले सकते हैं।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:21',
        startTimecode: '1:20',
        text: 'या छोड़ सकते हैं।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:27',
        startTimecode: '1:22',
        text: 'हर दिन जीने का तुम्हारा चुनाव, चाहे तुम मेरा सम्मान करो या अनादर, मुझे उससे कोई फर्क नहीं पड़ता।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:32',
        startTimecode: '1:29',
        text: 'एक तरह से या दूसरी तरह से।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:35',
        startTimecode: '1:32',
        text: 'तुम्हारे कर्म तुम्हारा भविष्य तय करेंगे, मेरा नहीं।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:37',
        startTimecode: '1:35',
        text: 'मैं प्रकृति हूँ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:38',
        startTimecode: '1:37',
        text: 'मैं आगे बढ़ती रहूँगी।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:42',
        startTimecode: '1:39',
        text: 'मैं विकसित होने के लिए तैयार हूँ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:45',
        startTimecode: '1:44',
        text: 'क्या तुम तैयार हो?',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:47',
        startTimecode: '1:45',
        text: 'प्रकृति को लोगों की जरूरत नहीं है।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:50',
        startTimecode: '1:48',
        text: 'लोगों को प्रकृति की जरूरत है।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
    ],
    pa: [
      {
        endTimecode: '0:05',
        startTimecode: '0:03',
        text: 'ਕੁਝ ਲੋਕ ਮੈਨੂੰ ਕੁਦਰਤ ਕਹਿੰਦੇ ਹਨ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:15',
        startTimecode: '0:11',
        text: 'ਦੂਸਰੇ ਮੈਨੂੰ ਮਾਂ ਕੁਦਰਤ ਕਹਿੰਦੇ ਹਨ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:26',
        startTimecode: '0:16',
        text: 'ਮੈਂ ਇੱਥੇ ਸਾਢੇ ਚਾਰ ਅਰਬ ਸਾਲਾਂ ਤੋਂ ਹਾਂ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:28',
        startTimecode: '0:26',
        text: 'ਤੁਹਾਡੇ ਮੁਕਾਬਲੇ 22,500 ਗੁਣਾ ਜ਼ਿਆਦਾ ਲੰਬਾ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:32',
        startTimecode: '0:29',
        text: 'ਮੈਨੂੰ ਲੋਕਾਂ ਦੀ ਅਸਲ ਵਿੱਚ ਲੋੜ ਨਹੀਂ ਹੈ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:35',
        startTimecode: '0:32',
        text: 'ਪਰ ਲੋਕਾਂ ਨੂੰ ਮੇਰੀ ਲੋੜ ਹੈ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:38',
        startTimecode: '0:36',
        text: "ਹਾਂ, ਤੁਹਾਡਾ ਭਵਿੱਖ ਮੇਰੇ 'ਤੇ ਨਿਰਭਰ ਕਰਦਾ ਹੈ।",
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:41',
        startTimecode: '0:38',
        text: 'ਜਦੋਂ ਮੈਂ ਵਧਦੀ ਫੁੱਲਦੀ ਹਾਂ, ਤਾਂ ਤੁਸੀਂ ਵਧਦੇ ਫੁੱਲਦੇ ਹੋ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:51',
        startTimecode: '0:43',
        text: 'ਜਦੋਂ ਮੈਂ ਡਗਮਗਾਉਂਦੀ ਹਾਂ, ਤਾਂ ਤੁਸੀਂ ਡਗਮਗਾਉਂਦੇ ਹੋ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:51',
        startTimecode: '0:51',
        text: 'ਜਾਂ ਬਦਤਰ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '0:58',
        startTimecode: '0:53',
        text: 'ਪਰ ਮੈਂ ਤਾਂ ਸਦੀਆਂ ਤੋਂ ਇੱਥੇ ਹਾਂ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:03',
        startTimecode: '0:58',
        text: 'ਮੈਂ ਤੁਹਾਡੇ ਤੋਂ ਮਹਾਨ ਪ੍ਰਜਾਤੀਆਂ ਨੂੰ ਭੋਜਨ ਦਿੱਤਾ ਹੈ, ਅਤੇ ਮੈਂ ਤੁਹਾਡੇ ਤੋਂ ਮਹਾਨ ਪ੍ਰਜਾਤੀਆਂ ਨੂੰ ਭੁੱਖਾ ਰੱਖਿਆ ਹੈ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:06',
        startTimecode: '1:04',
        text: 'ਮੇਰੇ ਮਹਾਂਸਾਗਰ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:08',
        startTimecode: '1:07',
        text: 'ਮੇਰੀ ਮਿੱਟੀ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:11',
        startTimecode: '1:09',
        text: 'ਮੇਰੀਆਂ ਵਗਦੀਆਂ ਧਾਰਾਵਾਂ, ਮੇਰੇ ਜੰਗਲ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:20',
        startTimecode: '1:16',
        text: 'ਉਹ ਸਭ ਤੁਹਾਨੂੰ ਲੈ ਸਕਦੇ ਹਨ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:21',
        startTimecode: '1:20',
        text: 'ਜਾਂ ਛੱਡ ਸਕਦੇ ਹਨ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:27',
        startTimecode: '1:22',
        text: 'ਹਰ ਦਿਨ ਜਿਉਣ ਦਾ ਤੁਹਾਡਾ ਚੋਣ, ਚਾਹੇ ਤੁਸੀਂ ਮੇਰਾ ਸਨਮਾਨ ਕਰੋ ਜਾਂ ਅਨਾਦਰ, ਮੈਨੂੰ ਉਸ ਤੋਂ ਕੋਈ ਫ਼ਰਕ ਨਹੀਂ ਪੈਂਦਾ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:32',
        startTimecode: '1:29',
        text: 'ਇੱਕ ਤਰ੍ਹਾਂ ਨਾਲ ਜਾਂ ਦੂਸਰੀ ਤਰ੍ਹਾਂ ਨਾਲ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:35',
        startTimecode: '1:32',
        text: 'ਤੁਹਾਡੇ ਕਰਮ ਤੁਹਾਡਾ ਭਵਿੱਖ ਤੈਅ ਕਰਨਗੇ, ਮੇਰਾ ਨਹੀਂ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:37',
        startTimecode: '1:35',
        text: 'ਮੈਂ ਕੁਦਰਤ ਹਾਂ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:38',
        startTimecode: '1:37',
        text: 'ਮੈਂ ਅੱਗੇ ਵਧਦੀ ਰਹਾਂਗੀ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:42',
        startTimecode: '1:39',
        text: 'ਮੈਂ ਵਿਕਸਤ ਹੋਣ ਲਈ ਤਿਆਰ ਹਾਂ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:45',
        startTimecode: '1:44',
        text: 'ਕੀ ਤੁਸੀਂ ਤਿਆਰ ਹੋ?',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:47',
        startTimecode: '1:45',
        text: 'ਕੁਦਰਤ ਨੂੰ ਲੋਕਾਂ ਦੀ ਲੋੜ ਨਹੀਂ ਹੈ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        endTimecode: '1:50',
        startTimecode: '1:48',
        text: 'ਲੋਕਾਂ ਨੂੰ ਕੁਦਰਤ ਦੀ ਲੋੜ ਹੈ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
    ],
  },
  chaptersVtt: [
    {
      chapterTitle: 'Introduction',
      timecode: '00:00',
    },
    {
      chapterTitle: "Nature's Perspective",
      timecode: '00:03',
    },
    {
      chapterTitle: 'Dependence on Nature',
      timecode: '00:32',
    },
    {
      chapterTitle: "Nature's Resilience",
      timecode: '00:52',
    },
    {
      chapterTitle: 'Human Actions and Consequences',
      timecode: '01:22',
    },
    {
      chapterTitle: 'Call to Action',
      timecode: '01:42',
    },
  ],
  description:
    "This video emphasizes the relationship between humans and nature. Nature narrates, stating it has existed for billions of years and doesn't need humans, but humans need nature for survival. The video calls for humans to consider their impact on the environment and highlights the idea that the future depends on preserving nature.",
  genres: ['Nature', 'Conservation', 'Environment'],
  imageGenerationPrompt:
    'Create a stunning visual showcasing the earth from space with emphasis on preserving nature and the importance of environmental conservation.',
  title: 'Nature Speaking',
} as any;
