export const mockAianalysisData = {
  title: 'Nature Speaks',
  description:
    "This powerful short film, narrated by Nature itself (voiced by Julia Roberts), takes viewers on a breathtaking journey across Earth's diverse landscapes—from towering mountains and vast oceans to lush forests and expansive deserts. It's a poignant reminder that while humanity relies heavily on Nature for survival, Nature has existed for eons and will continue to evolve, with or without us. The film implores viewers to consider their actions and their impact on the planet, underscoring the critical message: 'Nature doesn't need people. People need Nature.'",
  genres: ['Documentary', 'Environmental', 'Nature'],
  imageGenerationPrompt:
    "A panoramic, awe-inspiring shot of Earth from space, with a soft glow around the atmosphere. The upper half shows swirling white clouds and ice over vast blue oceans, while the lower half features landmasses with hints of green and brown. The sun's light subtly catches the curvature of the planet. The overall mood is majestic and contemplative, emphasizing the beauty and scale of nature. No text or watermarks.",
  chaptersVtt: [
    { timecode: '00:00:00.000', chapterTitle: "Nature's Identity" },
    { timecode: '00:00:16.800', chapterTitle: 'Ancient Existence' },
    { timecode: '00:00:32.400', chapterTitle: 'Human Dependence' },
    { timecode: '00:00:41.900', chapterTitle: 'Consequences of Actions' },
    { timecode: '00:00:58.700', chapterTitle: 'Eons of Resilience' },
    { timecode: '00:01:05.000', chapterTitle: "Nature's Domains" },
    { timecode: '00:01:21.500', chapterTitle: 'Your Fate, Not Mine' },
    { timecode: '00:01:39.500', chapterTitle: 'Nature Will Evolve' },
    { timecode: '00:01:45.000', chapterTitle: 'Final Message' },
  ],
  subtitles: {
    hi: [
      {
        startTimecode: '00:00:04.280',
        endTimecode: '00:00:05.900',
        text: 'कुछ लोग मुझे प्रकृति कहते हैं।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:13.880',
        endTimecode: '00:00:16.320',
        text: 'दूसरे मुझे माँ प्रकृति कहते हैं।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:16.800',
        endTimecode: '00:00:23.760',
        text: 'मैं यहाँ साढ़े चार अरब से भी अधिक वर्षों से हूँ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:24.400',
        endTimecode: '00:00:30.980',
        text: 'आपसे 22,500 गुना अधिक समय तक।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:32.400',
        endTimecode: '00:00:35.300',
        text: 'मुझे वास्तव में इंसानों की ज़रूरत नहीं है।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:36.000',
        endTimecode: '00:00:37.380',
        text: 'लेकिन इंसानों को मेरी ज़रूरत है।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:37.840',
        endTimecode: '00:00:41.700',
        text: 'हाँ, आपका भविष्य मुझ पर निर्भर करता है।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:41.900',
        endTimecode: '00:00:46.400',
        text: 'जब मैं फलती-फूलती हूँ, तो आप भी फलते-फूलते हैं।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:46.400',
        endTimecode: '00:00:50.840',
        text: 'जब मैं लड़खड़ाती हूँ, तो आप भी लड़खड़ाते हैं।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:51.630',
        endTimecode: '00:00:53.380',
        text: 'या इससे भी बुरा।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:53.940',
        endTimecode: '00:00:58.750',
        text: 'लेकिन मैं युगों से यहाँ हूँ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:58.750',
        endTimecode: '00:01:04.280',
        text: 'मैंने आपसे बड़ी प्रजातियों को पाला है, और मैंने आपसे बड़ी प्रजातियों को भूखा भी रखा है।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:05.000',
        endTimecode: '00:01:06.000',
        text: 'मेरे महासागर।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:07.460',
        endTimecode: '00:01:08.560',
        text: 'मेरी मिट्टी।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:09.680',
        endTimecode: '00:01:14.930',
        text: 'मेरी बहती धाराएँ, मेरे जंगल।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:16.030',
        endTimecode: '00:01:21.130',
        text: 'वे सब तुम्हें ले जा सकते हैं, या तुम्हें छोड़ सकते हैं।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:21.500',
        endTimecode: '00:01:28.980',
        text: 'आप हर दिन कैसे जीना चुनते हैं, चाहे आप मेरा सम्मान करें या अनादर, इससे मुझे कोई फर्क नहीं पड़ता।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:29.800',
        endTimecode: '00:01:31.900',
        text: 'किसी न किसी तरह।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:32.450',
        endTimecode: '00:01:36.520',
        text: 'आपके कार्य आपका भाग्य तय करेंगे, मेरा नहीं।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:36.720',
        endTimecode: '00:01:37.780',
        text: 'मैं प्रकृति हूँ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:38.000',
        endTimecode: '00:01:39.140',
        text: 'मैं चलती रहूँगी।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:39.500',
        endTimecode: '00:01:42.140',
        text: 'मैं विकसित होने के लिए तैयार हूँ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:44.820',
        endTimecode: '00:01:45.360',
        text: 'क्या तुम हो?',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
    ],
    pa: [
      {
        startTimecode: '00:00:04.280',
        endTimecode: '00:00:05.900',
        text: 'ਕੁਝ ਲੋਕ ਮੈਨੂੰ ਕੁਦਰਤ ਕਹਿੰਦੇ ਹਨ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:13.880',
        endTimecode: '00:00:16.320',
        text: 'ਦੂਸਰੇ ਮੈਨੂੰ ਮਾਂ ਕੁਦਰਤ ਕਹਿੰਦੇ ਹਨ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:16.800',
        endTimecode: '00:00:23.760',
        text: 'ਮੈਂ ਇੱਥੇ ਸਾਢੇ ਚਾਰ ਅਰਬ ਸਾਲਾਂ ਤੋਂ ਵੱਧ ਸਮੇਂ ਤੋਂ ਹਾਂ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:24.400',
        endTimecode: '00:00:30.980',
        text: 'ਤੁਹਾਡੇ ਨਾਲੋਂ 22,500 ਗੁਣਾ ਵੱਧ ਸਮੇਂ ਲਈ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:32.400',
        endTimecode: '00:00:35.300',
        text: 'ਮੈਨੂੰ ਅਸਲ ਵਿੱਚ ਲੋਕਾਂ ਦੀ ਲੋੜ ਨਹੀਂ ਹੈ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:36.000',
        endTimecode: '00:00:37.380',
        text: 'ਪਰ ਲੋਕਾਂ ਨੂੰ ਮੇਰੀ ਲੋੜ ਹੈ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:37.840',
        endTimecode: '00:00:41.700',
        text: "ਹਾਂ, ਤੁਹਾਡਾ ਭਵਿੱਖ ਮੇਰੇ 'ਤੇ ਨਿਰਭਰ ਕਰਦਾ ਹੈ।",
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:41.900',
        endTimecode: '00:00:46.400',
        text: 'ਜਦੋਂ ਮੈਂ ਵਧਦੀ-ਫੁੱਲਦੀ ਹਾਂ, ਤਾਂ ਤੁਸੀਂ ਵੀ ਵਧਦੇ-ਫੁੱਲਦੇ ਹੋ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:46.400',
        endTimecode: '00:00:50.840',
        text: 'ਜਦੋਂ ਮੈਂ ਡੋਲਦੀ ਹਾਂ, ਤਾਂ ਤੁਸੀਂ ਵੀ ਡੋਲਦੇ ਹੋ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:51.630',
        endTimecode: '00:00:53.380',
        text: 'ਜਾਂ ਇਸ ਤੋਂ ਵੀ ਬੁਰਾ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:53.940',
        endTimecode: '00:00:58.750',
        text: 'ਪਰ ਮੈਂ ਕਈ ਯੁੱਗਾਂ ਤੋਂ ਇੱਥੇ ਹਾਂ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:00:58.750',
        endTimecode: '00:01:04.280',
        text: 'ਮੈਂ ਤੁਹਾਡੇ ਨਾਲੋਂ ਵੱਡੀਆਂ ਪ੍ਰਜਾਤੀਆਂ ਨੂੰ ਪਾਲਿਆ ਹੈ, ਅਤੇ ਮੈਂ ਤੁਹਾਡੇ ਨਾਲੋਂ ਵੱਡੀਆਂ ਪ੍ਰਜਾਤੀਆਂ ਨੂੰ ਭੁੱਖਾ ਵੀ ਰੱਖਿਆ ਹੈ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:05.000',
        endTimecode: '00:01:06.000',
        text: 'ਮੇਰੇ ਸਮੁੰਦਰ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:07.460',
        endTimecode: '00:01:08.560',
        text: 'ਮੇਰੀ ਮਿੱਟੀ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:09.680',
        endTimecode: '00:01:14.930',
        text: 'ਮੇਰੀਆਂ ਵਗਦੀਆਂ ਨਦੀਆਂ, ਮੇਰੇ ਜੰਗਲ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:16.030',
        endTimecode: '00:01:21.130',
        text: 'ਉਹ ਸਭ ਤੁਹਾਨੂੰ ਲੈ ਜਾ ਸਕਦੇ ਹਨ, ਜਾਂ ਤੁਹਾਨੂੰ ਛੱਡ ਸਕਦੇ ਹਨ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:21.500',
        endTimecode: '00:01:28.980',
        text: 'ਤੁਸੀਂ ਹਰ ਰੋਜ਼ ਕਿਵੇਂ ਜੀਣਾ ਚੁਣਦੇ ਹੋ, ਭਾਵੇਂ ਤੁਸੀਂ ਮੇਰਾ ਸਤਿਕਾਰ ਕਰੋ ਜਾਂ ਅਪਮਾਨ, ਇਸ ਨਾਲ ਮੈਨੂੰ ਕੋਈ ਫਰਕ ਨਹੀਂ ਪੈਂਦਾ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:29.800',
        endTimecode: '00:01:31.900',
        text: 'ਇੱਕ ਨਾ ਇੱਕ ਤਰੀਕੇ ਨਾਲ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:32.450',
        endTimecode: '00:01:36.520',
        text: 'ਤੁਹਾਡੇ ਕੰਮ ਤੁਹਾਡੀ ਕਿਸਮਤ ਨਿਰਧਾਰਤ ਕਰਨਗੇ, ਮੇਰੀ ਨਹੀਂ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:36.720',
        endTimecode: '00:01:37.780',
        text: 'ਮੈਂ ਕੁਦਰਤ ਹਾਂ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:38.000',
        endTimecode: '00:01:39.140',
        text: 'ਮੈਂ ਚਲਦੀ ਰਹਾਂਗੀ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:39.500',
        endTimecode: '00:01:42.140',
        text: 'ਮੈਂ ਵਿਕਸਤ ਹੋਣ ਲਈ ਤਿਆਰ ਹਾਂ।',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
      {
        startTimecode: '00:01:44.820',
        endTimecode: '00:01:45.360',
        text: 'ਕੀ ਤੁਸੀਂ ਹੋ?',
        voiceGender: 'female',
        voiceType: 'neutral',
      },
    ],
  },
  geminiTtsPrompts: {
    style:
      'A calm, narrative, slightly melancholic voice, like a powerful documentary narrator, conveying wisdom and ancient perspective.',
    hi: "Start: 00:00:04.280 ('neutral, calm') say: कुछ लोग मुझे प्रकृति कहते हैं।\\nStart: 00:00:13.880 ('neutral, calm') say: दूसरे मुझे माँ प्रकृति कहते हैं।\\nStart: 00:00:16.800 ('neutral, wise') say: मैं यहाँ साढ़े चार अरब से भी अधिक वर्षों से हूँ।\\nStart: 00:00:24.400 ('neutral, wise') say: आपसे 22,500 गुना अधिक समय तक।\\nStart: 00:00:32.400 ('neutral, firm') say: मुझे वास्तव में इंसानों की ज़रूरत नहीं है।\\nStart: 00:00:36.000 ('neutral, firm') say: लेकिन इंसानों को मेरी ज़रूरत है।\\nStart: 00:00:37.840 ('neutral, serious') say: हाँ, आपका भविष्य मुझ पर निर्भर करता है।\\nStart: 00:00:41.900 ('neutral, calm') say: जब मैं फलती-फूलती हूँ, तो आप भी फलते-फूलते हैं।\\nStart: 00:00:46.400 ('neutral, concerned') say: जब मैं लड़खड़ाती हूँ, तो आप भी लड़खड़ाते हैं।\\nStart: 00:00:51.630 ('neutral, ominous') say: या इससे भी बुरा।\\nStart: 00:00:53.940 ('neutral, wise') say: लेकिन मैं युगों से यहाँ हूँ।\\nStart: 00:00:58.750 ('neutral, firm') say: मैंने आपसे बड़ी प्रजातियों को पाला है, और मैंने आपसे बड़ी प्रजातियों को भूखा भी रखा है।\\nStart: 00:01:05.000 ('neutral, proud') say: मेरे महासागर।\\nStart: 00:01:07.460 ('neutral, proud') say: मेरी मिट्टी।\\nStart: 00:01:09.680 ('neutral, proud') say: मेरी बहती धाराएँ, मेरे जंगल।\\nStart: 00:01:16.030 ('neutral, firm') say: वे सब तुम्हें ले जा सकते हैं, या तुम्हें छोड़ सकते हैं।\\nStart: 00:01:21.500 ('neutral, detached') say: आप हर दिन कैसे जीना चुनते हैं, चाहे आप मेरा सम्मान करें या अनादर, इससे मुझे कोई फर्क नहीं पड़ता।\\nStart: 00:01:29.800 ('neutral, firm') say: किसी न किसी तरह।\\nStart: 00:01:32.450 ('neutral, authoritative') say: आपके कार्य आपका भाग्य तय करेंगे, मेरा नहीं।\\nStart: 00:01:36.720 ('neutral, strong') say: मैं प्रकृति हूँ।\\nStart: 00:01:38.000 ('neutral, resolute') say: मैं चलती रहूँगी।\\nStart: 00:01:39.500 ('neutral, confident') say: मैं विकसित होने के लिए तैयार हूँ।\\nStart: 00:01:44.820 ('neutral, questioning') say: क्या तुम हो?",
    pa: "Start: 00:00:04.280 ('neutral, calm') say: ਕੁਝ ਲੋਕ ਮੈਨੂੰ ਕੁਦਰਤ ਕਹਿੰਦੇ ਹਨ।\\nStart: 00:00:13.880 ('neutral, calm') say: ਦੂਸਰੇ ਮੈਨੂੰ ਮਾਂ ਕੁਦਰਤ ਕਹਿੰਦੇ ਹਨ।\\nStart: 00:00:16.800 ('neutral, wise') say: ਮੈਂ ਇੱਥੇ ਸਾਢੇ ਚਾਰ ਅਰਬ ਸਾਲਾਂ ਤੋਂ ਵੱਧ ਸਮੇਂ ਤੋਂ ਹਾਂ।\\nStart: 00:00:24.400 ('neutral, wise') say: ਤੁਹਾਡੇ ਨਾਲੋਂ 22,500 ਗੁਣਾ ਵੱਧ ਸਮੇਂ ਲਈ।\\nStart: 00:00:32.400 ('neutral, firm') say: ਮੈਨੂੰ ਅਸਲ ਵਿੱਚ ਲੋਕਾਂ ਦੀ ਲੋੜ ਨਹੀਂ ਹੈ।\\nStart: 00:00:36.000 ('neutral, firm') say: ਪਰ ਲੋਕਾਂ ਨੂੰ ਮੇਰੀ ਲੋੜ ਹੈ।\\nStart: 00:00:37.840 ('neutral, serious') say: ਹਾਂ, ਤੁਹਾਡਾ ਭਵਿੱਖ ਮੇਰੇ 'ਤੇ ਨਿਰਭਰ ਕਰਦਾ ਹੈ।\\nStart: 00:00:41.900 ('neutral, calm') say: ਜਦੋਂ ਮੈਂ ਵਧਦੀ-ਫੁੱਲਦੀ ਹਾਂ, ਤਾਂ ਤੁਸੀਂ ਵੀ ਵਧਦੇ-ਫੁੱਲਦੇ ਹੋ।\\nStart: 00:00:46.400 ('neutral, concerned') say: ਜਦੋਂ ਮੈਂ ਡੋਲਦੀ ਹਾਂ, ਤਾਂ ਤੁਸੀਂ ਵੀ ਡੋਲਦੇ ਹੋ।\\nStart: 00:00:51.630 ('neutral, ominous') say: ਜਾਂ ਇਸ ਤੋਂ ਵੀ ਬੁਰਾ।\\nStart: 00:00:53.940 ('neutral, wise') say: ਪਰ ਮੈਂ ਕਈ ਯੁੱਗਾਂ ਤੋਂ ਇੱਥੇ ਹਾਂ।\\nStart: 00:00:58.750 ('neutral, firm') say: ਮੈਂ ਤੁਹਾਡੇ ਨਾਲੋਂ ਵੱਡੀਆਂ ਪ੍ਰਜਾਤੀਆਂ ਨੂੰ ਪਾਲਿਆ ਹੈ, ਅਤੇ ਮੈਂ ਤੁਹਾਡੇ ਨਾਲੋਂ ਵੱਡੀਆਂ ਪ੍ਰਜਾਤੀਆਂ ਨੂੰ ਭੁੱਖਾ ਵੀ ਰੱਖਿਆ ਹੈ।\\nStart: 00:01:05.000 ('neutral, proud') say: ਮੇਰੇ ਸਮੁੰਦਰ।\\nStart: 00:01:07.460 ('neutral, proud') say: ਮੇਰੀ ਮਿੱਟੀ।\\nStart: 00:01:09.680 ('neutral, proud') say: ਮੇਰੀਆਂ ਵਗਦੀਆਂ ਨਦੀਆਂ, ਮੇਰੇ ਜੰਗਲ।\\nStart: 00:01:16.030 ('neutral, firm') say: ਉਹ ਸਭ ਤੁਹਾਨੂੰ ਲੈ ਜਾ ਸਕਦੇ ਹਨ, ਜਾਂ ਤੁਹਾਨੂੰ ਛੱਡ ਸਕਦੇ ਹਨ।\\nStart: 00:01:21.500 ('neutral, detached') say: ਤੁਸੀਂ ਹਰ ਰੋਜ਼ ਕਿਵੇਂ ਜੀਣਾ ਚੁਣਦੇ ਹੋ, ਭਾਵੇਂ ਤੁਸੀਂ ਮੇਰਾ ਸਤਿਕਾਰ ਕਰੋ ਜਾਂ ਅਪਮਾਨ, ਇਸ ਨਾਲ ਮੈਨੂੰ ਕੋਈ ਫਰਕ ਨਹੀਂ ਪੈਂਦਾ।\\nStart: 00:01:29.800 ('neutral, firm') say: ਇੱਕ ਨਾ ਇੱਕ ਤਰੀਕੇ ਨਾਲ।\\nStart: 00:01:32.450 ('neutral, authoritative') say: ਤੁਹਾਡੇ ਕੰਮ ਤੁਹਾਡੀ ਕਿਸਮਤ ਨਿਰਧਾਰਤ ਕਰਨਗੇ, ਮੇਰੀ ਨਹੀਂ।\\nStart: 00:01:36.720 ('neutral, strong') say: ਮੈਂ ਕੁਦਰਤ ਹਾਂ।\\nStart: 00:01:38.000 ('neutral, resolute') say: ਮੈਂ ਚਲਦੀ ਰਹਾਂਗੀ।\\nStart: 00:01:39.500 ('neutral, confident') say: ਮੈਂ ਵਿਕਸਤ ਹੋਣ ਲਈ ਤਿਆਰ ਹਾਂ।\\nStart: 00:01:44.820 ('neutral, questioning') say: ਕੀ ਤੁਸੀਂ ਹੋ?",
  },
};

export const mockImagePaths = {
  posterImagePath: 'mock/ai-generated/mock-poster.png',
  backdropImagePath: 'mock/ai-generated/mock-backdrop.png',
};

export const mockAudioPaths = {
  hi: 'mock/sample.hi.dubbed.mp3',
  pa: 'mock/sample.pa.dubbed.mp3',
};
